import React from 'react';
import {
  Bot,
  Search,
  BarChart3,
  PenTool,
  Zap,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  MessageSquare,
  Rocket,
  Trash2,
  ClipboardList,
  Settings,
  User,
  Clock,
  TrendingUp,
  Link,
  Hourglass,
  RefreshCw,
  Brain,
  LayoutDashboard
} from 'lucide-react';

export const Icons = {
  Researcher: Search,
  Coder: Bot, // using Bot as a generic technical icon or we can use Code
  Analyst: BarChart3,
  Writer: PenTool,
  Assistant: Bot,
  Dashboard: LayoutDashboard,
  Workflows: Zap,
  Agents: User,
  Success: CheckCircle2,
  Error: XCircle,
  Warning: AlertTriangle,
  Chat: MessageSquare,
  Run: Rocket,
  Delete: Trash2,
  Tasks: ClipboardList,
  Config: Settings,
  Time: Clock,
  Growth: TrendingUp,
  Connection: Link,
  Pending: Hourglass,
  Processing: RefreshCw,
  Brain: Brain,
};
